language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

dist: trusty
sudo: false

install: travis_retry composer install --no-interaction --prefer-source
script: travis_retry composer dump-autoload --optimize
script: vendor/bin/phpunit --verbose
